mudler/LocalAGI

requirements.txt
Build failed due to missing langchain-community package in requirements.txt.
=> Add langchain-community requirement to make it build again

webui/react-ui/src/pages/AgentStatus.jsx, webui/routes.go
The new UI copied the old one, but the old rendered a template in Go.
=> fix(ui): Don't try to pass unserializable Go objects to status UI

README.md, docker-compose.intel.yaml, docker-compose.nvidia.yaml, docker-compose.yaml
Fixes https://github.com/mudler/LocalAGI/issues/49
Switching to sd-1.5 as it's much smaller. Models can be changed easily as described by the docs
=> fix: correct image name, switch to sd-1.5-ggml as default

core/action/state.go, core/agent/actions.go, core/agent/agent.go, core/agent/observer.go, core/agent/options.go, core/agent/state.go, core/state/pool.go, core/types/job.go, core/types/observable.go, core/types/state.go, webui/app.go, webui/react-ui/bun.lock, webui/react-ui/package.json, webui/react-ui/src/App.css, webui/react-ui/src/hooks/useSSE.js, webui/react-ui/src/pages/AgentStatus.jsx, webui/routes.go
This builds on (or replaces) the status view with structured events.
The idea is that each time the agent performs some action, like making a decision
using the LLM, the UI will show a group of nested boxes that the user can drill
down into.
At the top level are incoming events with trigger the agent and then a series of
actions it has to perform to respond to the event. At the lowest level we have
the actual API requests to LocalAI or a tool. The lower levels will be hidden
by default.
The observable API allows showing what events are in progress and which have
been completed. So that the user can see what asynchronous actions are waiting 
to be completed.
- **refactor(ui): Make message status SSE name more specific**
- **feat(ui): Add structured observability events**
Note that in the …
=> feat(ui): Structured observability/status view

core/agent/observer.go, core/state/pool.go, services/connectors/irc.go, webui/app.go, webui/react-ui/src/pages/AgentStatus.jsx
Keep some agent start across restarts, such as the SSE manager and
observer. This allows restarts to be shown on the state page and also
allows avatars to be kept when reconfiguring the agent.
Also observable updates can happen out of order because SSE manager has
multiple workers. For now handle this in the client.
Finally fix an issue with the IRC client to make it disconnect and
handle being assigned a different nickname by the server.
=> fix: Handle state on agent restart and update observables

services/connectors/discord.go
This should fix #79 .
The token should be prefixed with "Bot", however that is confusing in term of UX - with this change we support both (token with or without prefix) as we add it automatically if missing.
=> fix(discord): automatically add 'Bot' prefix to token if missing

docker-compose.intel.yaml, docker-compose.nvidia.yaml
Need to specify the service in the extended Docker compose files
=> fix(docker): Add mcpbox server to extended compose files

Dockerfile.mcpbox
As much as I love alpine, we will have less issues with ubuntu as majority of mcp stuff works out of the box there.
=> chore(mcpbox): use ubuntu:24.04 as base

core/state/config.go
There is a huge performance improvement (at least with local models) when deep reasoning is enabled
=> chore(defaults): Enable reasoning by default

webui/react-ui/src/pages/ActionsPlayground.jsx
I love this project, I noticed there was a json error in the actions playground after changing the number of search results.
This request changes values for fieldType number to String for unmarshalling to avoid the error.
=> fix(playground): convert fieldType number to string for json unmarshalling

services/actions.go, services/actions/sendtelegrammessage.go
This pull request introduces a new action for sending Telegram messages, enhancing the functionality of the `services/actions` package. The most important changes include adding a new action type (`ActionSendTelegramMessage`), implementing the corresponding runner (`SendTelegramMessageRunner`), and updating configuration metadata to support this new action.
* **Action Type and Registration**:
- Added a new action type `ActionSendTelegramMessage` to the list of available actions in `services/actions.go`. This includes its registration in constants, the `AvailableActions` array, and the action dispatcher logic. [[1]](diffhunk://#diff-5aab8777508cb5e7d38317a653464faff7f84bd4efab292aa10dbf599827b4f7R49) [[2]](diffhunk://#diff-5aab8777508cb5e7d38317a653464faff7f84bd4efab292aa10dbf599827b4f7R83) …
=> feat(telegram): add action to send telegram message

README.md, go.mod, go.sum, services/connectors.go, services/connectors/email.go
Inspired by how long some of my agents take to respond, I've created an email provider to match their pace.
With the email connector configured, the user can send an email to the agent, and the agent will reply to the user.
- Support conversational chat (replies)
- Can send and receive HTML emails
- Supports secure and insecure IMAP + SMTP
- Only listens to the email address configured (in case user has multiple emails)
- Markdown is formatted correctly in HTML emails
- Inline images (when the agent outputs them in markdown syntax)
- DKIM signing
- File attachments
I've created this connector for my own IMAP and SMTP servers, and I don't have any others. I assume others will work but if they do not, I'd be more than happy to work with everyone to get that solved and to get this merged …
=> feat: email connector

services/actions/shell.go
- If command exit code != 0, the command output was never displayed to the agent, only the exit code.
- If a command had no output, agents frequently thought the command never ran. The reasoning will then get stuck in a loop trying to run the same command, even though it's run successfully.
=> fix: errored ssh output

.github/workflows/image.yml, Dockerfile.sshbox, README.md, docker-compose.yaml, main.go, services/actions.go, services/actions/shell.go
This PR adds a specific service "sshbox" that is connected directly to LocalAGI. It is a container running sshd which is set with root/root as default. This can be changed easily by configuring the docker-compose file and tweaking the environment variables as needed.
When LOCALAGI_SSHBOX_URL is set, the ssh action can be picked up without configuration and will give agents automatically access to the sshbox.
=> feat(sshbox): add sshbox to run commands

README.md, services/connectors/telegram.go
Now the bot can be added to groups - in order for this to work correctly you have to turn off privacy mode in groups from Botfather
=> feat(telegram): Add support for groups

main.go
When in a panic, it would be nice to know which env key needs to be corrected. ;)
=> fix: use correct env key in panic

README.md, docker-compose.amd.yaml
Adding docker-compose.amd.yaml to run easily LocalAGI on AMD gpu. 
I tested it on Archlinux with AMD RX6950XT gpu
=> Add docker compose for amd gpu

webui/react-ui/src/pages/AgentStatus.jsx
This prevents React from crashing when an image is submitted on its own, but doesn't provide the best UX. Displaying the contents of a multimedia or multi-part message is left to a future PR. Possibly we need to stop using the raw chat completion API output and normalise the messages server side which is beyond the scope of just preventing a crash.
=> fix(ui): Avoid passing object (multimedia message) into React template

README.md, main.go, services/actions.go
This PR allows to specify a `LOCALAGI_CUSTOM_ACTIONS_DIR` which can contain a set of actions as described already in https://github.com/mudler/LocalAGI?tab=readme-ov-file#1-custom-actions-go-code
=> feat(custom actions): allow to specify a dir with all custom actions

core/action/custom.go, core/state/config.go, services/actions.go, services/prompts.go, services/prompts/custom.go
This is useful mainly to pass-by from the web interface a generic string that can be later re-used in the custom actions or dynamic prompt during Init().
The Signature of the custom actions and prompts around Init has changed, and now is Init(string), this is on the custom action duty to decide if the string is e.g. a JSON, or a comma separated list, etc.
=> feat(actions/dynamicprompt): allow to pass-by a configuration

services/actions.go, services/actions/webhook.go
This PR adds a new webhook action that enables LocalAGI agents to send HTTP requests to external services.
The action requires static configuration:
- url (required): Target endpoint
- method: HTTP method (defaults to POST)
- contentType: Content-Type header value
- payloadTemplate: Optional body template with {{payload}} placeholder
Runtime parameters accept only the dynamic payload value, keeping the action simple.
This action enables agents to:
- Trigger external webhooks and integrations
- Post data to third-party APIs
- Perform GET requests to fetch external data
Note, I currently only tested it in the "actions playground", I didn't test it inside an agent yet.
=> Add webhook action for HTTP request integration

webui/react-ui/src/components/ActionForm.jsx, webui/react-ui/src/components/ConfigForm.jsx, webui/react-ui/src/components/agent-form-sections/ActionsSection.jsx, webui/react-ui/src/pages/ActionsPlayground.jsx
This PR adds a "Play" button to the action list in the agent configuration. When clicking it, the actions playground opens in a new window with the action pre-selected and all fields pre-filled.
This allows for easier debugging, because the parameters configured for an action inside an agent don't to be entered again in the playground.
=> Add "Play" button to action configuration for testing in Playground
