mudler/LocalAGI

requirements.txt

And add newline at the end of the file (v. important)

Pin openai API to pre v1.0

---

webui/react-ui/vite.config.js

fix(ui): Proxy avatars endpoint in dev mode

---

core/agent/agent_test.go

fix(test): Encourage LLM to plan multiple searches

---

services/actions.go
services/actions/githubprcreator.go
services/actions/githubprcreator_test.go
services/actions/githubprreviewer_test.go
services/actions/githubrepositorygetallcontent.go
services/actions/githubrepositorygetallcontent_test.go

Part of https://github.com/mudler/LocalAGI/issues/35

feat(github): add action to open up a PR and get all repository content

---

core/agent/agent.go
core/agent/options.go
core/state/config.go
core/state/pool.go

feat: allow the agent to perform things concurrently

---

pkg/localoperator/client.go
services/actions/browseragentrunner.go
services/connectors/slack.go
slack.yaml

This will allow the bot to post screenshots of the last action that was taken by the browser agent

feat(browseragent): post screenshot on slack

---

core/action/custom.go
webui/app.go
webui/react-ui/src/pages/ActionsPlayground.jsx
webui/react-ui/src/utils/api.js
webui/react-ui/src/utils/config.js
webui/routes.go

- **feat(ui): Action playground config and parameter forms**
Add some better input forms for the action playground. Instead of entering raw JSON.
TODO:

feat(ui): Action playground config and parameter forms

---

README.md
core/agent/agent.go
core/types/observable.go
webui/react-ui/src/components/CollapsibleRawSections.jsx
webui/react-ui/src/pages/AgentStatus.jsx

Trys to extract the details from each observable that sum up their purpose, inputs and output

feat(ui,observability): Add summary details for observables

---

.github/workflows/tests.yml
core/agent/actions.go
core/agent/agent.go
core/agent/options.go

Originally part of the mock LLM PR, but I seperated it out because it shouldn't be held back.

fix(core): Add recursive loop detection and move loop detection

---

core/agent/agent.go

Small fixup to cleanup LLM answers based on Agent settings

fix: cleanup responses also when not picking any tool

---

services/actions.go
services/actions/githubissueedit.go

Tested in https://github.com/mudler/LocalAGI/issues/59

feat(github): add issue editor

---

services/actions.go

This should fix https://github.com/mudler/LocalAGI/issues/103

fix(actions): make sure to initialize a config

---

README.md
core/agent/agent.go
core/agent/options.go
core/state/config.go
core/state/pool.go
core/types/filters.go
core/types/job.go
core/types/observable.go
main.go
services/filters.go
services/filters/classifier.go
services/filters/regex.go
webui/app.go
webui/react-ui/src/components/AgentForm.jsx
webui/react-ui/src/components/ConfigForm.jsx
webui/react-ui/src/components/FilterForm.jsx
webui/react-ui/src/components/agent-form-sections/FiltersSection.jsx
webui/react-ui/src/pages/AgentStatus.jsx
webui/react-ui/src/utils/api.js

Implements #96
Video: https://youtu.be/d_we-AYksSw
TODO:

feat(filters): Add configurable filters for incoming jobs

---

services/actions.go
services/actions/callagents.go

This allows to allow certain agents to be called

feat(call_agents): allow to specify whitelist and blacklist agents

---

core/agent/agent.go
core/agent/evaluation.go
core/agent/identity.go
core/agent/options.go
core/state/config.go
core/state/pool.go
core/types/job.go
pkg/llm/json.go
services/filters/classifier.go
webui/app.go

This PR adds a deep evaluation mechanism to allow the agent to backtrack and fill the gaps if it miss the author ask. It is configurable with a max loop.

feat(evaluation): add deep evaluation mechanism

---

core/agent/agent.go
core/agent/knowledgebase.go

KB items were not being included in the chat.

fix(core): Add prompt generated from KB to conv

---

Makefile
README.md
core/agent/actions.go
docker-compose.yaml

feat: improve parameter generation by forcing reasoning

---

webui/types/openai.go

Partially fixes: #163
Tool calls are not handled and the types need adding AFAICT

fix(api): Use RawMessage for nested polymorphic JSON in OpenAI request input

---

core/agent/actions.go
core/agent/agent.go
core/types/actions.go
core/types/job.go
pkg/client/responses.go
pkg/utils/ptr/ptr.go
tests/e2e/e2e_test.go
webui/app.go
webui/types/openai.go

Fixes: #163
EDIT: There is still a lot we could do with built-in actions instead of just validating them, but I'm inclined towards moving that to a later PR.

feat(api): Handle tool calls in responses API

---

docker-compose.yaml

fix(docker): Update model and backend directories

---

core/agent/actions.go
core/agent/agent.go
core/agent/prompt.go
core/types/actions.go
core/types/prompts.go
services/prompts/custom.go
services/prompts/memory.go

This allows actions and dynamic prompts to return images and being described. This allows, for instance, to have actions generating images and the system can describe, or act on them again.

feat: multimodal action and dynamic prompts results

---

webui/react-ui/src/components/AgentForm.jsx
webui/react-ui/src/components/agent-form-sections/PromptsGoalsSection.jsx

fix(ui): Correct typos in dynamic prompts

---

services/actions.go
services/actions/pikvm.go

This adds a very simple action to control a host ATX power state via pikvm (on, off, reset, etc)

feat(actions): add action to control pikvm

---

core/agent/agent.go
core/agent/options.go
core/state/config.go
core/state/pool.go
main.go
services/connectors/telegram.go

This PR adds basic support for audio transcription and generation in the agent, and adds support for it with telegram

feat: add audio support
